function A = rotation(angle, ux, uy, uz)
    
    % calculate a rotation matrix to rotate a vector an angle about
    % the axis [ux uy uz]

    A = [...
        cos(angle)+ux*ux*(1-cos(angle))    ux*uy*(1-cos(angle))+uz*sin(angle) ux*uz*(1-cos(angle))-uy*sin(angle) ;...
        ux*uy*(1-cos(angle))-uz*sin(angle) cos(angle)+uy*uy*(1-cos(angle))    uy*uz*(1-cos(angle))+ux*sin(angle) ;...
        ux*uz*(1-cos(angle))+uy*sin(angle) uy*uz*(1-cos(angle))-ux*sin(angle) cos(angle)+uz*uz*(1-cos(angle))   ;...
        ];
end